name: RealPlugin
main: fr.crafter.tickleman.realplugin.RealPluginPlugin
version: 1.02
website: http://plugins.crafter.fr/tickleman/RealPlugin/
author: tickleman
softdepend: [Permissions,Register,Spout,Vault]
commands:
  realplugin:
    aliases: [rp]
    description: RealPlugin plugins manager
    usage: /rp help
