name: RealPlugin
main: fr.crafter.tickleman.realplugin.RealPluginPlugin
version: 1.07
website: http://plugins.crafter.fr/tickleman/RealPlugin/
author: tickleman
load: STARTUP
commands:
  realplugin:
    aliases: [rp]
    description: RealPlugin plugins manager
    usage: /rp help
